### ISSUE TITLE
[ERROR] NPC causes Unknown entity id field: org.slf4j.Logger

### ISSUE THREAD

**Issue by x1p** [re-ovo/Matrix-Issues#2506]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.17 server // No, I'm on 1.18.2
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.18.2 and Purpur 1.18.2
**Error(s) found in console**: 
```
[09:26:40 INFO]: Spawned KillAura Npc for Player123abc (120 ticks)
[09:26:40 INFO]: [Matrix] [STDOUT] Unknown entity id field: org.slf4j.Logger
[09:26:40 WARN]: Nag author(s): '[RE]' of 'Matrix' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[09:26:40 INFO]: [Matrix] [STDOUT] Warning: Failed to generate the entity id: git-Paper-252 (MC: 1.18.2) t: non-fie
```
**How/when does this happen**: after the command `matrix npc player 120`
**Other information**: On my production server there is a longer error containing maybe some more information:
```
[09:37:03 INFO]: Unknown entity id field: org.slf4j.Logger
[09:37:03 INFO]: Warning: Failed to generate the entity id: git-Purpur-1593 (MC: 1.18.2) t: non-fie
[09:37:03 WARN]: [ProtocolLib] Loaded class me.rerere.matrix.internal.x from Matrix v6.7.0 which is not a depend or softdepend of this plugin.
[09:37:03 WARN]: FieldAccessException: Field index out of bounds. (Index: 2, Size: 2)
[09:37:03 WARN]: at ProtocolLib-547.jar//com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:373)
[09:37:03 WARN]: at ProtocolLib-547.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:349)
[09:37:03 WARN]: at Matrix_6.7.0_beta06.jar//me.rerere.matrix.internal.x.x(Unknown Source)
[09:37:03 WARN]: at Matrix_6.7.0_beta06.jar//me.rerere.matrix.internal.xn.x(Unknown Source)
[09:37:03 WARN]: at Matrix_6.7.0_beta06.jar//me.rerere.matrix.internal.tg.run(Unknown Source)
[09:37:03 WARN]: at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[09:37:03 WARN]: at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[09:37:03 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1558)
[09:37:03 WARN]: at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[09:37:03 WARN]: at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1482)
[09:37:03 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
[09:37:03 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[09:37:03 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[09:37:03 INFO]: [Matrix/TickTask] Error happened! check: KILLAURA type: com.comphenix.protocol.reflect.FieldAccessException
```
Tested with Paper and Purpur in combination with Protocollib build 547 and 551

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by Kylepoops** [comment]
Will be fixed in next beta
